version: '3.1'

services:
  backend_web:
    restart: always
    environment:
      _UVICORN_HOST: "0.0.0.0"
      _UVICORN_PORT: 8001
      _PG_HOST: "postgres"
    build:
      context: .
      dockerfile: DockerfileWeb
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - "./app/.env:/backend/app/.env"
    ports:
      - 8001:8001

  postgres:
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_USER: db_main
      POSTGRES_PASSWORD: db_main
      PGUSER: db_main
      PGPASSWORD: db_main
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./extra/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./app/data/pg/:/var/lib/postgresql/data/
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.3-bookworm
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1
    volumes:
      - ./app/data/redis/:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    networks:
      - backend

networks:
  backend:
    name: backend
