version: '3.1'

services:
  backend_web:
    restart: always
    environment:
      _UVICORN_HOST: "0.0.0.0"
      _UVICORN_PORT: 8000
      _PG_HOST: "postgres"
    build:
      context: .
      dockerfile: DockerfileWeb
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8000:8000

  postgres:
    image: postgis/postgis:16-3.4-alpine
    environment:
      PGUSER: db_main
      PGPASSWORD: db_main
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./extra/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./app/data/pg/:/var/lib/postgresql/data/
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend:
    name: backend
