import enum


class OfficeFeature(str, enum.Enum):
    INDIVIDUAL_MORTGAGE_LENDING = "INDIVIDUAL_MORTGAGE_LENDING"
    INDIVIDUAL_DEPOSITS = "INDIVIDUAL_DEPOSITS"
    INDIVIDUAL_CURRENCY_EXCHANGE_OPERATIONS = "INDIVIDUAL_CURRENCY_EXCHANGE_OPERATIONS"

    LEGAL_ENTITY_LENDING = "LEGAL_ENTITY_LENDING"
    LEGAL_ENTITY_SETTLEMENT_SERVICE = "LEGAL_ENTITY_SETTLEMENT_SERVICE"

    AVAILABLE_WITH_LIMITED_MOBILITY = "AVAILABLE_WITH_LIMITED_MOBILITY"
    IS_WORKING_NOW = "IS_WORKING_NOW"
